/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nordsec.norddrop;

public class libnorddropJNI {
  public final static native int NORDDROP_LOG_CRITICAL_get();
  public final static native int NORDDROP_LOG_ERROR_get();
  public final static native int NORDDROP_LOG_WARNING_get();
  public final static native int NORDDROP_LOG_INFO_get();
  public final static native int NORDDROP_LOG_DEBUG_get();
  public final static native int NORDDROP_LOG_TRACE_get();
  public final static native int NORDDROP_RES_OK_get();
  public final static native int NORDDROP_RES_ERROR_get();
  public final static native int NORDDROP_RES_INVALID_STRING_get();
  public final static native int NORDDROP_RES_BAD_INPUT_get();
  public final static native int NORDDROP_RES_JSON_PARSE_get();
  public final static native int NORDDROP_RES_TRANSFER_CREATE_get();
  public final static native int NORDDROP_RES_NOT_STARTED_get();
  public final static native int NORDDROP_RES_ADDR_IN_USE_get();
  public final static native int NORDDROP_RES_INSTANCE_START_get();
  public final static native int NORDDROP_RES_INSTANCE_STOP_get();
  public final static native int NORDDROP_RES_INVALID_PRIVKEY_get();
  public final static native int NORDDROP_RES_DB_ERROR_get();
  public final static native long new_NordDrop__SWIG_0(INordDropEventCb jarg1, int jarg2, INordDropLoggerCb jarg3, INordDropPubkeyCb jarg4, byte[] jarg5, INordDropFdCb jarg6);
  public final static native long new_NordDrop__SWIG_1(INordDropEventCb jarg1, int jarg2, INordDropLoggerCb jarg3, INordDropPubkeyCb jarg4, byte[] jarg5);
  public final static native void delete_NordDrop(long jarg1);
  public final static native int NordDrop_start(long jarg1, NordDrop jarg1_, String jarg2, String jarg3);
  public final static native int NordDrop_stop(long jarg1, NordDrop jarg1_);
  public final static native int NordDrop_cancelTransfer(long jarg1, NordDrop jarg1_, String jarg2);
  public final static native int NordDrop_rejectFile(long jarg1, NordDrop jarg1_, String jarg2, String jarg3);
  public final static native int NordDrop_download(long jarg1, NordDrop jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native String NordDrop_newTransfer(long jarg1, NordDrop jarg1_, String jarg2, String jarg3);
  public final static native int NordDrop_purgeTransfers(long jarg1, NordDrop jarg1_, String jarg2);
  public final static native int NordDrop_purgeTransfersUntil(long jarg1, NordDrop jarg1_, long jarg2);
  public final static native int NordDrop_removeTransferFile(long jarg1, NordDrop jarg1_, String jarg2, String jarg3);
  public final static native int NordDrop_setPeerState(long jarg1, NordDrop jarg1_, String jarg2, int jarg3);
  public final static native String NordDrop_getTransfersSince(long jarg1, NordDrop jarg1_, long jarg2);
  public final static native String NordDrop_version();
}
