[package]
name = "drop-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
ed25519-dalek = "1.0.1"
rand = "0.8.5"
