[package]
name = "drop-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
rand = "0.8.5"
hmac = "0.12.1"
x25519-dalek = "1.2.0"
sha2 = "0.10.6"
