name: Analytics tests
run-name: ${{ github.actor }} is running analytics tests
on:
  - push
  - pull_request_target
jobs:
  tests:
    runs-on: ubuntu-latest    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.1
          default: true        
      - name: docker sdk
        run: |
          pip3 install docker 
      - name: Print docker version
        run: docker version
      - name: Build Docker image
        run: docker build -t libdroptestimage test
      - name: Print images
        run: docker images
      - name: run tests
        run: |
          SCENARIO="analytics.*" make -C test
  
