name: Build and Push to GitHub Container Registry

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev


jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/nordsecurity/libdrop/testimage:1.0.0 test

    - name: Push Docker image to GitHub Container Registry
      if: github.event_name == 'push'
      run: docker push ghcr.io/nordsecurity/libdrop/testimage:1.0.0
