name: GitLab CI Pipeline
on:
  pull_request_target:
    types: [labeled]
  push:
  schedule:
    # Avoid running on 0 since a lot of other workflows on github start at that
    # time and this can cause delays or even dropping of jobs:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: 26 23,10 * * *
permissions: {}

jobs:
  trigger-gitlab-pipeline:
    uses: NordSecurity/trigger-gitlab-pipeline/.github/workflows/trigger-gitlab-pipeline.yml@22c73479b495367b1c8e6ee40145c75a3b4b6706
    secrets:
      ci-api-v4-url: ${{ secrets.CI_API_V4_URL }}
      access-token: ${{ secrets.GITLAB_API_TOKEN }}
      trigger-token: ${{ secrets.TOKEN }}
      project-id: ${{ secrets.PROJECT_ID }}
    with:
      schedule: ${{ github.event_name == 'schedule' }}
      cancel-outdated-pipelines: ${{ github.ref_name != 'main' }}
      triggered-ref:  msz/FILE-641-migrate-to-codehub

