name: Trigger GitLab pipeline
on:
  pull_request_target:
    branches: [dev, main]
    types: [labeled]
  push:
    branches: [dev, main]
    tags:
      - v*
permissions: {}
jobs:
  trigger-gitlab-pipeline:
    runs-on: [self-hosted, gitlab]
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'gitlab')) }}
    steps:
      - uses: NordSecurity/trigger-gitlab-pipeline@940714dbb5c77428fb13ecdb3a94cf929adfb65e # v2.0.0
        with:
          ci-api-v4-url: ${{ secrets.CI_API_V4_URL }}
          access-token: ${{ secrets.GITLAB_API_TOKEN }}
          trigger-token: ${{ secrets.TOKEN }}
          project-id: ${{ secrets.PROJECT_ID }}
          cancel-outdated-pipelines: ${{ github.ref_name != 'main' && github.ref_name != 'dev' }}
          triggered-ref: LLT-623_fix_macos_paths 

